### ISSUE TITLE
Add public document for the new logger

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/soft#102]
Please add public document about how to use the new logger with different parameters.

**Comment by bkokoszx** [comment]
Logger instructions has been added to README file and it was merged to master.

**Comment by bkokoszx** [comment]
@mengdonglin There was also update made by @mmaka1 to developer guides in sof-docs:
https://github.com/thesofproject/sof-docs/pull/51

**Comment by akloniex** [comment]
@mengdonglin Please verify if current documentation is sufficient and update this issue accordingly.

**Comment by mengdonglin** [comment]
@akloniex @mmaka1 Thank you for the document! I close the issue.
