### ISSUE TITLE
DMIC doesn't support stereo recording on Yorp

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/soft#120]
The latest sof-glk-da7219.tplg doesn't support stereo recording.
tested with: 
soft-master:4ac9248f
sof-master:43da16
kernel-debug/cros-v4.14-rebase: 90eee4
chronos@localhost ~ $ sudo arecord -Dhw:0,99 -f S32_LE -c 2 -r 48000 test.wav
Recording WAVE 'test.wav' : Signed 32 bit Little Endian, Rate 48000 Hz, Stereo
arecord: set_params:1345: Channels count non available

**Comment by mengdonglin** [comment]
Need https://github.com/thesofproject/soft/pull/119/

**Comment by lgirdwood** [comment]
@keqiaozhang  #119 now merged.

**Comment by keqiaozhang** [comment]
This issue is fixed by PR #119
