### ISSUE TITLE
default_hw_conf_id should not be set to 0

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/soft#15]
default_hw_conf_id should be the id that in the configs list.
Be 0 will let most hw_config not set in function 
static void set_link_hw_format(struct snd_soc_dai_link *link, struct snd_soc_tplg_link_config *cfg)
https://github.com/thesofproject/linux/blob/cb05347d9f85e18b414098d512c8287c297933d2/sound/soc/soc-topology.c#L2015

**Comment by keqiaozhang** [comment]
This issue is fixed by https://github.com/thesofproject/soft/pull/16
