### ISSUE TITLE
compile error "unknown section SectionVendorTokens"

### ISSUE THREAD

**Issue by musiclvme** [thesofproject/soft#21]
**compile host machine info:**
Ubuntu 16.04
aplay: version 1.1.0---> It indicates that Ubuntu16.04 is using ALSA-lib 1.10 version?

**error log as follow:**
Compiling test test-capture -> test-capture-dmic0-MONO_PDM0_MICA-passthrough-s16le-s16le-8k-nocodec.tplg
ALSA lib ctl.c:214:(tplg_parse_tlv_dbscale)  scale: vtlv_m90s3

ALSA lib ctl.c:239:(tplg_parse_tlv_dbscale) 	min = -6400

ALSA lib ctl.c:239:(tplg_parse_tlv_dbscale) 	step = 200

ALSA lib ctl.c:239:(tplg_parse_tlv_dbscale) 	mute = 1

ALSA lib parser.c:175:(tplg_parse_config) error: unknown section SectionVendorTokens

ALSA lib parser.c:175:(tplg_parse_config) error: unknown section SectionVendorTuples

ALSA lib dapm.c:446:(tplg_parse_dapm_widget)  Widget: PCM0C

ALSA lib dapm.c:469:(tplg_parse_dapm_widget) 	index: 2

ALSA lib dapm.c:485:(tplg_parse_dapm_widget) 	type: aif_out

ALSA lib dapm.c:496:(tplg_parse_dapm_widget) 	no_pm: true

ALSA lib parser.c:278:(snd_tplg_build_file) error: failed to parse topology

failed to compile context test-capture-dmic0-MONO_PDM0_MICA-passthrough-s16le-s16le-8k-nocodec.conf

**Comment by xiulipan** [comment]
This is because you are using low verison alsa-lib

SectionVendorTokens is some update not in Ubuntu 16.04
And we need some newer fix for alsa-lib for dai direction.

For the newest SOFT repo, you need to build the topology with alsa-lib master branch (I think 1.1.6 + is needed) due to above update.

**Comment by xiulipan** [comment]
You will need to 
`git clone git://git.alsa-project.org/alsa-lib.git`
`cd alsa-lib`
`./gitcompile`
`sudo make install`

This will install the newest libasound into /usr/lib/
To update the alsa-lib in Ubuntu you need to manually replace libasound.so.2 in /usr/lib/x86_64-linux-gnu/ with the installed on in /usr/lib/
