### ISSUE TITLE
rimage:no rimage would be installed 

### ISSUE THREAD

**Issue by musiclvme** [thesofproject/soft#24]
**follow these cmds to compile the whole project:**
./autogen.sh
./configure
make
make install

only rmbox is installed in /usr/local/bin, but **rimage** is not existed? (sof.git project would use rimage to make bin)

**Comment by ranj063** [comment]
@musiclvme rimage is part of the SOF repo. Please take a look at scripts/xtensa-build-all.sh. It builds and installs rimage before compiling the firmware. Hope this helps!

**Comment by xiulipan** [comment]
@musiclvme 
Where do you get this guide?
It seems they are outdated.

**Comment by musiclvme** [comment]
@xiulipan 
https://www.alsa-project.org/main/index.php/Firmware 
this page is not updated?

**Comment by xiulipan** [comment]
@musiclvme 
sorry, this seems to be outdated.
We are writing new version doc now. You can see README files in the sof to see if there is any changes. That file should have some update.
Sorry for the inconvenience。

**Comment by musiclvme** [comment]
@ranj063 @xiulipan   thanks !
I would go to sof project to check it.
