### ISSUE TITLE
fail to load test-ssp4-mclk-0-I2S-volume-s16le-s16le-48k-24576k-codec.tplg  on GP platform

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/soft#27]
env:
sof-dev ：a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof:           6b94226b81efc8a71cc01d962f460fa5a7fa850d
soft:         47339d2302f445c3b35d50f9720ee649dd2f739b
using topology/test/test-ssp4-mclk-0-I2S-volume-s16le-s16le-48k-24576k-codec.tplg as sof-apl-tdf8532.tplg
dmesg log:
 sof-audio sof-audio: ASoC: physical link SSP4-Codec (id 0) not exist
[    7.201159] sof-audio sof-audio: error: tplg component load failed -22
[    7.201171] sof-audio sof-audio: error: failed to load DSP topology -22
[    7.201173] sof-audio sof-audio: ASoC: failed to probe component -22
[    7.201193] bxt_tdf8532 bxt_tdf8532: ASoC: failed to instantiate card -22

**Comment by xiulipan** [comment]
@zhuqingliang 
pleaes did not use test topology on GP since the machine driver has multiple dai support and need a careful written topology.

**Comment by xiulipan** [comment]
[  224.923379] sof-audio sof-audio: ipc rx: 0x600a0000 done
[  224.925155] sof-audio sof-audio: pcm: trigger stream 0 dir 0 cmd 1
[  224.925184] sof-audio sof-audio: ipc: send 0x60040000
[  224.925347] sof-audio sof-audio: ipc: 0x60040000 succeeded
[  224.928411] sof-audio sof-audio: posn mailbox: posn offset is 0xc1000
[  224.928420] sof-audio sof-audio: posn XRUN: host 0 comp 4 size -192
[  224.928425] sof-audio sof-audio: ipc rx: 0x60090000 done
[  225.512009] sof-audio sof-audio: pcm: trigger stream 0 dir 0 cmd 0
[  225.512088] sof-audio sof-audio: ipc: send 0x60050000
[  225.816287] sof-audio sof-audio: error: ipc timed out for 0x60050000 size 0xc
[  225.816307] sof-audio sof-audio: status: fw entered - code 00000005
[  225.816333] sof-audio sof-audio: error: runtime exception
[  225.816339] sof-audio sof-audio: error: trace point 00004000
[  225.816347] sof-audio sof-audio: error: DSP Firmware Oops
[  225.816354] sof-audio sof-audio: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
[  225.816363] sof-audio sof-audio: EXCCAUSE 0x0000000d EXCVADDR 0x09574645 PS       0x00070025 SAR     0x00000010
[  225.816371] sof-audio sof-audio: EPC1     0xbe01c969 EPC2     0xbe01c95f EPC3     0xbe010b82 EPC4    0x00000000
[  225.816379] sof-audio sof-audio: EPC5     0xbe021e79 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[  225.816387] sof-audio sof-audio: EPS2     0x00060120 EPS3     0x00060520 EPS4     0x00000000 EPS5    0x00060022
[  225.816395] sof-audio sof-audio: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x000101d8 INTERRU 0x00000222
[  225.816402] sof-audio sof-audio: stack dump from 0xbe07ff40
[  225.816410] sof-audio sof-audio: 0xbe07ff40: 0xbe01c969 0x00000000 0x00000010 0x00000000
[  225.816419] sof-audio sof-audio: 0xbe07ff44: 0xbe044024 0x00000000 0x09574645 0x00000000
[  225.816427] sof-audio sof-audio: 0xbe07ff48: 0x0000000d 0x00000000 0xbe0226a6 0xbe0226bc
[  225.816435] sof-audio sof-audio: 0xbe07ff4c: 0xfda04119 0x00000000 0xbe044024 0x00000000
[  225.816444] sof-audio sof-audio: 0xbe07ff50: 0xbeef0011 0x00000000 0x00000002 0x00000000
[  225.816452] sof-audio sof-audio: 0xbe07ff54: 0x7e0104c6 0x00000000 0x00004000 0x00000000
[  225.816460] sof-audio sof-audio: 0xbe07ff58: 0x09574645 0x00000000 0x00030082 0xbe054800
[  225.816468] sof-audio sof-audio: 0xbe07ff5c: 0x00000000 0x00000000 0x01000000 0x00000000
[  225.816475] sof-audio sof-audio: error: waking up any trace sleepers
[  225.816497]  Passthrough: ASoC: trigger FE failed -110
[  225.818939] sof-audio sof-audio: pcm: trigger stream 0 dir 0 cmd 1

here is the part dmesg that the error hapens

**Comment by lgirdwood** [comment]
@xiulipan stack dump shows that 0x09574645 is being passed in as argument to function that crashes.

**Comment by xiulipan** [comment]
@lgirdwood this log should goes to https://github.com/thesofproject/sof/issues/19
Yes, that is the basic error here. But still could not find the call trace to this function. It just like we have a wrong context and the code just run into it and caused this panic. Do you have any idea that may let the PC jump to some place without a call stack?

**Comment by xiulipan** [comment]
@zhuqingliang 
GP should not use test topology anymore since it have multiple BE that have various dai id rather then 0.

**Comment by lgirdwood** [comment]
@xiulipan please check the 0xbe addresses in the stack trace with the disassembly.  This will show the functions being called up to the crash point as you are not far down in the stack. It looks like the crash has happened in IRQ level 5 (reading PS[3..0] and the prior to IRQ level 5 we were in IRQ level 2 EPS5[3..0]). EPC1 -> EPC2 ->EPC5 will show interrupt execution order.

**Comment by plbossart** [comment]
On 7/16/18 5:00 AM, xiulipan wrote:
> @zhuqingliang <https://github.com/zhuqingliang>
> GP should not use test topology anymore since it have multiple BE that 
> have various dai id rather then 0.

We want test topologies to be usable even if the dai id is not zero.

**Comment by xiulipan** [comment]
@plbossart 
Then maybe we need one more filed for the dai id in the name for the topology, And this should be just passed to the scripts.

**Comment by xiulipan** [comment]
@lgirdwood 
That is cool, I was reading the reference manual and could not tell what all these register mean. I will recheck the code and with the manual. 
Thanks

**Comment by plbossart** [comment]
On 07/16/2018 10:31 PM, xiulipan wrote:
>
> @plbossart <https://github.com/plbossart>
> Then maybe we need one more filed for the dai id in the name for the 
> topology, And this should be just passed to the scripts.
>
yes indeed.

**Comment by mengdonglin** [comment]
Close this issue for there is no user request for this platform atm. It can be reopened if situation changes.
