### ISSUE TITLE
Fail to load topology/sof-apl-pcm512x.tplg on up^2

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/soft#29]
environment:
sof-dev: a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof: 2d92796
soft: 47339d2302f445c3b35d50f9720ee649dd2f739b

**Comment by lgirdwood** [comment]
We appear to be missing logs. I will close this until logs are added.

**Comment by zhuqingliang** [comment]
The bug is fixed in 2abbfc0910ce9767d01462638d719309746844d1.

**Comment by keqiaozhang** [comment]
This issue is fixed by https://github.com/thesofproject/soft/pull/28
