### ISSUE TITLE
missing DMIC topology in test

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/soft#38]
miss DMIC test topology in test topology.
Need to add

**Comment by singalsu** [comment]
I'm proposing to make for UP2 (nocodec mode) a passtrough capture topology with 4ch, and an IIR EQ capture topology with high-pass filter (e.g. 50 Hz) and +20 dB boost. The latter would provide capture signal level that's common with various recording equipment.

**Comment by singalsu** [comment]
@xiulipan There's now two topologies sof-apl-dmic-2ch.m4 and sof-apl-dmic-4ch.m4 those provide the raw stream. There's also topology sof-apl-eq-dmic.m4 that provides a DSP high-pass filter for ensuring the DC removal (originates from the microphone component) is complete and provides +20 dB gain for more usual recording sensitivity. Please close this if that works for you!

**Comment by xiulipan** [comment]
@singalsu 
That would be work.
Thanks
