### ISSUE TITLE
'error log' in dmesg when boot up on CNL using sof-cnl-rt274.tplg

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/soft#46]
description:
run dmesg once boot up , but aplay and arecord work well.

[ 5.645901] cnl_rt274 cnl_rt274: snd-soc-dummy-dai <-> Passthrough 0 mapping ok
[ 5.645962] cnl_rt274 cnl_rt274: ASoC: no sink widget found for Dummy Playback
[ 5.645965] cnl_rt274 cnl_rt274: ASoC: Failed to add route ssp2 Tx -> direct -> Dummy Playback
[ 5.645968] cnl_rt274 cnl_rt274: ASoC: no source widget found for ssp2_out
[ 5.645970] cnl_rt274 cnl_rt274: ASoC: Failed to add route ssp2_out -> direct -> ssp2 Tx
[ 5.645974] cnl_rt274 cnl_rt274: ASoC: no source widget found for Dummy Capture
[ 5.645977] cnl_rt274 cnl_rt274: ASoC: Failed to add route Dummy Capture -> direct -> ssp2 Rx
[ 5.645980] cnl_rt274 cnl_rt274: ASoC: no sink widget found for ssp2_in
[ 5.645982] cnl_rt274 cnl_rt274: ASoC: Failed to add route ssp2 Rx -> direct -> ssp2_in
[ 5.645986] cnl_rt274 cnl_rt274: ASoC: no sink widget found for Dummy Playback
[ 5.645989] cnl_rt274 cnl_rt274: ASoC: Failed to add route ssp1 Tx -> direct -> Dummy Playback
[ 5.645993] cnl_rt274 cnl_rt274: ASoC: no source widget found for ssp1_out
[ 5.645996] cnl_rt274 cnl_rt274: ASoC: Failed to add route ssp1_out -> direct -> ssp1 Tx
[ 5.646797] input: sof-cnl-audio Headset as /devices/pci0000:00/0000:00:1f.3/cnl_rt274/sound/card0/input8

System Environment:
sof-dev: b78ead1e0cd31113bc1b3b6d122c9afc1a344147
sof: a2cfd8c
soft: debaf8f889607406159a13f8bba7d7218243683d
using topology/sof-cnl-rt274.tplg

reproduce steps:
dmesg

log:
[dmesg.log](https://github.com/thesofproject/soft/files/2244803/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/soft/files/2244805/rmbox-t.log)

**Comment by lgirdwood** [comment]
Topology is missing DAPM route connections.

**Comment by zhuqingliang** [comment]
reproduced with 91bb08dd8ce6305bda1649d0171c48456ba75421

**Comment by keqiaozhang** [comment]
This issue still can be reproduced with latest code base and also the soundcard name is wrong.
**** List of PLAYBACK Hardware Devices ****
card 0: sofsofsofsofsof [sof-sof-sof-sof-sof-sof-sof-sof], device 0: Passthrough (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by plbossart** [comment]
The topology file needs to be fixed to add the relevant virtual widgets/routes to make the warnings go away.
For the card name, it's fixed upstream and will be applied when we move to 4.18.

**Comment by juimonen** [comment]
I think in soft debaf8f the virtual routes and widgets are in the topology file (?). With Ranjani's plotter I can see the connection.
At least in the attached dmesg file the parser ignores those widgets (don't know if this is what should happen).
After sof parsing the asoc tries to connect something to "ssp1 tx" and "spp2 tx", also "ssp1 out". The virtual widgets in the topology file are something like "ssp0 tx" and "codec0_out". Should these match?

just my 2 cents...

**Comment by RanderWang** [comment]
fixed by https://github.com/thesofproject/soft/pull/55
