### ISSUE TITLE
Need rmbox update for debugability update in SOF

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/soft#75]
after https://github.com/thesofproject/sof/pull/390
The rmbox could not read the new format

**Comment by xiulipan** [comment]
@akloniex 
Could not assign to you.
Please assign to whom is working on this.

**Comment by akloniex** [comment]
@bkokoszx is working on the subject. Although I cannot assign him due to lack of permissions in this repository.

**Comment by mengdonglin** [comment]
@lgirdwood @xiulipan Close this issue since we're going to use the new logger tool?
https://github.com/thesofproject/soft/pull/77

**Comment by xiulipan** [comment]
Close via #77
