### ISSUE TITLE
 tplgs loading failed on  BYT

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/soft#9]
commit : f756455e90156f5b4965e8ab2751d26619dff9e0
On APL , tplg is 'test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg'
the log is
[    5.451061] sof-audio sof-audio: error: can't connect DAI SSP5.OUT stream NoCodec-5
[    5.451627] sof-audio sof-audio: error: can't connect DAI SSP5.IN stream NoCodec-5
[    5.456527] sof-audio sof-audio: error: tplg component load failed -22
[    5.456537] sof-audio sof-audio: error: failed to load DSP topology -22

On CNL, tplg is 'test-ssp0-mclk-0-I2S-volume-s16le-s16le-48k-24000k-nocodec.tplg
the log is
[    3.448094] sof-audio sof-audio: error: can't connect DAI SSP0.OUT stream NoCodec-0
[    3.449932] sof-audio sof-audio: error: can't connect DAI SSP0.IN stream NoCodec-0
[    3.452223] sof-audio sof-audio: error: tplg component load failed -22
[    3.452265] sof-audio sof-audio: error: failed to load DSP topology -22
[    3.484232] sof-nocodec: probe of sof-nocodec failed with error -22

On BYT, tplg is 'test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-codec.tplg'
the log is
[    9.739730] sof-audio sof-audio: ASoC: physical link SSP2-Codec (id 2) not exist
[    9.739735] sof-audio sof-audio: error: tplg component load failed -22
[    9.739746] sof-audio sof-audio: error: failed to load DSP topology -22
[    9.739749] sof-audio sof-audio: ASoC: failed to probe component -22
[    9.739799] bytcr_rt5651 bytcr_rt5651: ASoC: failed to instantiate card -22
[    9.752215] bytcr_rt5651 bytcr_rt5651: Topology forgot to remove link Passthrough?
[    9.768074] bytcr_rt5651 bytcr_rt5651: devm_snd_soc_register_card failed -22

**Comment by plbossart** [comment]
This is a known issue due to dependencies on the kernel PR2 which hasn't been approved yet

**Comment by xiulipan** [comment]
Test with the kernel PR2.
With BYT RT5651, there will be a mismatch bug when try to find  physical link SSP2-Codec (id 2)
The machine have a dai with  SSP2-Codec (id 0)
The new topology will make the id 0 => 2.
I check the topology patch set and find 
[patch here 0 => TEST_DAI_PORT](https://github.com/keyonjie/soft/blob/9ac2e32099f5f6409ddf95ddd5ce634bcbaa4e0d/topology/test/test-all.m4#L88)
cause the regression on codec platform.

**Comment by keyonjie** [comment]
we need to set the 3rd params of DAI_CONFIG() to be the corresponding .id defined in machine driver Be dai_links, so we may need add a param for codec test topology generation.

**Comment by zhuqingliang** [comment]
Now commit 629d2a6bf1d0cf3c5b069d06fd120ed43ef5040f
test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg  load successfully on APl 
test-ssp0-mclk-0-I2S-volume-s16le-s16le-48k-24000k-nocodec.tplg load successfully on CNL

**Comment by zhuqingliang** [comment]
commit  629d2a6bf1d0cf3c5b069d06fd120ed43ef5040f  
nocodec tplg load successfully on APL and CNL

**Comment by xiulipan** [comment]
should be fixed with https://github.com/thesofproject/soft/pull/19

**Comment by lgirdwood** [comment]
@zhuqingliang please close this if all is working

**Comment by zhuqingliang** [comment]
"test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-codec.tplg " load success on commit 

ff8eb10b1877bb0fac8adf0124c36762a5f912fd
--

**Comment by keqiaozhang** [comment]
This bug is fixed by https://github.com/thesofproject/soft/pull/19
