### ISSUE TITLE
Logger does not show timestamps as time

### ISSUE THREAD

**Issue by singalsu** [thesofproject/soft#94]
The old rmbox printed handy timestamps with seconds as measure unit. It was easy to see e.g. how long the copy() operation for a component took in microseconds and convert that to a (coarse) MCPS value. The new logger shows timestamp only as a counter value. Could this be changed back to time?

It also would help a lot to compare side by side kernel dmesg and firmware logs.

**Comment by mengdonglin** [comment]
@singalsu Which platform are you using?

**Comment by mengdonglin** [comment]
@ZhendanYang Could you reproduce this issue on Minnowboard or UP2 platform?

**Comment by akloniex** [comment]
@singalsu @mengdonglin 
Feature was implemented during unification of rmbox and logger tools: https://github.com/thesofproject/soft/pull/88 merged 3 days ago.
-c parameter allows to specify clock rate, with default 19.2, similarly as rmbox did.

Please check current version.

**Comment by singalsu** [comment]
That sounds excellent, I'll test it and close this. I'm anyways using a script due to more command line parameters required for typical usage so it's easy to add the -c for clock rate there.

**Comment by mengdonglin** [comment]
@akloniex Could you help to submit a PR for a README, as a user guide for the new logger?
Or could you guide us to the document if it's ready there? Thanks

**Comment by cujomalainey** [comment]
Please make sure this documentation is available publically.

**Comment by singalsu** [comment]
@akloniex OK, now when I use executable /usr/local/bin/logger it works and shows with -c 19.2 the time as expected.

However why was the name changed back to logger?  I have also on my computer /usr/bin/logger from Ubuntu package bsdutils for totally different purpose. I'll close this anyway since the executable name is another discussion.

**Comment by singalsu** [comment]
Closing

**Comment by mengdonglin** [comment]
@singalsu I saw PR #105 is renaming the new logger name from logger to sof_logger.
